Repository RedHatInsights/topological_inventory-providers-common, pull requests merged in 2020-10, with the labels that each got.

#55 Add Operations Async Worker class
  lib/topological_inventory/providers/common/operations/async_worker.rb
  spec/topological_inventory/providers/common/operations/async_worker_spec.rb
Labels: enhancement

#56 Release v1.0.12
  CHANGELOG.md
  lib/topological_inventory/providers/common/version.rb
Labels: hacktoberfest-accepted

#53 Changelog 2.0.0
  CHANGELOG.md
  lib/topological_inventory/providers/common/version.rb
Labels: unmergeable

#54 Add availability checks for sources by kafka
  lib/topological_inventory/providers/common/messaging_client.rb
  lib/topological_inventory/providers/common/operations/source.rb
  spec/support/shared/availability_check.rb
  topological_inventory-providers-common.gemspec
Labels: enhancement
